export interface IData {
  countries: string[];
  names: string[];
  colors: string[];
  objects: string[];
}

export const data: IData = {
  countries: [
    "United States",
    "United Kingdom",
    "New Zealand",
    "Costa Rica",
    "Saudi Arabia",
    "United Arab Emirates",
    "South Africa",
    "North Korea",
    "South Korea",
    "Germany",
    "France",
    "Argentina",
    "Chile",
    "Colombia",
    "Venezuela",
    "Peru",
    "Ecuador",
  ],
  names: [
    "Christopher",
    "Garcia",
    "Gonzalez",
    "Lopez",
    "Hernandez",
    "Perez",
    "Martinez",
    "Gutierrez",
    "Rodriguez",
    "Sanchez",
  ],
  colors: [
    "red",
    "blue",
    "green",
    "yellow",
    "orange",
    "purple",
    "pink",
    "brown",
    "black",
    "white",
  ],
  objects: [
    "Mobile phone",
    "Stylus pen",
    "Soup spoon",
    "Rechargeable battery",
    "Solar lamp",
    "Folding table",
    "table",
    "chair",
    "bed",
    "book",
    "pencil",
    "pen",
    "laptop",
    "keyboard",
    "mouse",
    "monitor",
  ],
};
